### ISSUE TITLE
Sanjana Markdown

### ISSUE THREAD

**Issue by SanjanaBoggaram** [dscpesu/my-first-opensource-contribution#247]
Project Request to update [your name] markdown file and route

---

| Field  | Description                       |
| ------ | --------------------------------- |
| Name | Sanjana Boggaram J |
| Email  | sanjana.boggaram28@gmail.com                               |
| Github | SanjanaBoggaram                  |

---https://github.com/SanjanaBoggaram

**What do you what to contribute to:**

- [ ] HackFest GDSC Contributor
- [ ] Hacktober Fest Contributor

**Comment by keerthan44** [comment]
Remove ---.
