### ISSUE TITLE
Add S_P_Suhas Markdown

### ISSUE THREAD

**Issue by skillfulsuhas** [dscpesu/my-first-opensource-contribution#269]
## Project Request

Proejct Request to Add [your name] markdown file and route

---

| Field  | Description                       |
| ------ | --------------------------------- |
| Name | S P Suhas |
| Email  | spsuhas2004@gmail.com|
| Github | skillfulsuhas  |

---

**What do you what to contribute to:**

- [ ] HackFest GDSC Contributor
- [ ] Hacktober Fest Contributor

**Comment by capnmav77** [comment]
Please add your github link
